name: Push to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build
        run: |
          npm install -g @angular/cli
          npm ci
          ng deploy --repo=https://github.com/mfcar/MusicLinkSharing.git --name=musiclinksharing --email=$EMAIL --message="Build from ${GITHUB_SHA} in the source repository." --branch=main
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUBTOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
